In [1]:
import numpy as np

# 1. Créer un tableau 2D de taille 4x5 contenant des entiers de 10 à 29 inclus
matrice = np.arange(10, 30).reshape(4, 5)

# 2. Afficher le nombre de dimensions, la forme et le type des éléments
print("Nombre de dimensions :", matrice.ndim)
print("Forme du tableau :", matrice.shape)
print("Type des éléments :", matrice.dtype)

# 3. Afficher la moyenne, l’écart-type et le maximum
print("Moyenne :", matrice.mean())
print("Écart-type :", matrice.std())
print("Maximum :", matrice.max())

# 4. Aplatir le tableau, puis le retransformer en 5x4
aplat = matrice.flatten()
matrice_5x4 = aplat.reshape(5, 4)

print("Tableau aplati :", aplat)
print("Reconverti en 5x4 :\n", matrice_5x4)


Nombre de dimensions : 2
Forme du tableau : (4, 5)
Type des éléments : int64
Moyenne : 19.5
Écart-type : 5.766281297335398
Maximum : 29
Tableau aplati : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Reconverti en 5x4 :
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]


In [ ]:
import numpy as np

# 1. Générer deux tableaux 1D
a = np.arange(0, 10)
b = np.arange(10, 20)

# 2. Transformer en matrices 2D de forme (2, 5)
a_mat = a.reshape(2, 5)
b_mat = b.reshape(2, 5)

# 3. Calculer la somme des deux matrices
somme = a_mat + b_mat
print("Somme des matrices :\n", somme)

# 4. Concaténation horizontale et verticale
concat_h = np.hstack((a_mat, b_mat))
concat_v = np.vstack((a_mat, b_mat))

print("Concaténation horizontale :\n", concat_h)
print("Concaténation verticale :\n", concat_v)
    
# 5. Afficher la deuxième ligne du tableau verticalement concaténé
print("Deuxième ligne concaténée verticalement :", concat_v[1])


Somme des matrices :
 [[10 12 14 16 18]
 [20 22 24 26 28]]
Concaténation horizontale :
 [[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]
Concaténation verticale :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Deuxième ligne concaténée verticalement : [5 6 7 8 9]
